name: Java release

on:
  release:
    branches: [ "main" ]

env:
  DOCKER_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPOSITORY: java_tasktracker_ui

jobs:
  build:
    name: Build and push release version of Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Set tag environment variable
        id: set_tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
      - name: Build docker repo
        run: docker build -t ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}:${{ steps.set_tag.outputs.SOURCE_TAG }} .
      - name: Push to Docker Hub
        run: docker push ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_REPOSITORY }}:${{ steps.set_tag.outputs.SOURCE_TAG }}